openapi: 3.0.1
info:
  title: Events
  description: Export from "apim-rr-prod-centralus-001"
  version: '1.0'
paths:
  /:
    post:
      summary: Events
      operationId: post-logevent
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
