openapi: 3.0.1
info:
  title: ReadyRemit
  description: "Export from apim-rr-prod-centralus-001 06/04/25"
  version: v2
paths:
  '/transfer-requests/{id}':
    get:
      tags:
        - TransferRequest
      summary: GetTransferRequestAsync
      description: GetTransferRequestAsync
      operationId: gettransferrequestasync
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
        '403':
          description: ''
        '404':
          description: ''
  '/transfer-requests/{id}/verifications':
    post:
      summary: PostTransferRequestVerificationAsync
      description: PostTransferRequestVerificationAsync
      operationId: posttransferrequestverificationasync
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
        '403':
          description: ''
        '404':
          description: ''
  '/transfer-requests/{id}/submit':
    put:
      summary: SubmitTransferRequestAsync
      description: SubmitTransferRequestAsync
      operationId: submittransferrequestasync
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
        '403':
          description: ''
        '404':
          description: ''
  /customer/settings:
    get:
      tags:
        - TransferRequest
      summary: GetCustomerSettingsAsync
      description: GetCustomerSettingsAsync
      operationId: getcustomersettingsasync
      responses:
        '200':
          description: ''
        '403':
          description: ''
        '404':
          description: ''
  '/transfer-requests/{id}/cancel':
    post:
      summary: CancelTransferRequestAsync
      description: CancelTransferRequestAsync
      operationId: canceltransferrequestasync
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
        '403':
          description: ''
  /transfer-requests/bulk:
    post:
      summary: CreateTransferRequestAsync
      operationId: createtransferrequestasync
      responses:
        '200':
          description: 
  /transfer-requests:
    post:
      summary: GetTransferRequests
      operationId: gettransferrequests
      responses:
        '200':
          description: 
  /users:
    post:
      summary: CreateUser
      operationId: createuser
      responses:
        '200':
          description: 
  '/users/{id}/deactivate':
    patch:
      summary: DeactivateUser
      operationId: deactivateuser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/users/{id}':
    patch:
      summary: UpdateUser
      operationId: updateuser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/users/{id}/change-password':
    post:
      summary: ChangePassword
      operationId: changepassword
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/transfer-requests/{id}/receipt':
    get:
      summary: GetTransferRequestReceipt
      operationId: gettransferrequestreceipt
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  /oauth/token:
    post:
      summary: oAuth Token
      operationId: oauth-token
      responses:
        '200':
          description: 
  '/transfer-requests/{id}/resend-invitation':
    post:
      summary: PostTransferRequestsResendInvitation
      operationId: posttransferrequestsresendinvitation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/users/{id}/activate':
    patch:
      summary: ActivateUser
      operationId: activateuser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/users/{id}/reset-mfa':
    post:
      summary: PostUserResetMfa
      operationId: postuserresetmfa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/transfer-requests/{id}/notes':
    post:
      summary: CreateTranserRequestNotes
      operationId: createtranserrequestnotes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/transfer-requests/{id}/reissue':
    post:
      summary: ReissueTransferRequest
      operationId: reissuetransferrequest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/users/{id}/resend-invitation':
    post:
      summary: ResendPortalInvite
      operationId: resendportalinvite
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  /recipient-portal-sessions:
    post:
      summary: CreateRecipientPortalSession
      operationId: createrecipientportalsession
      responses:
        '200':
          description: 
  '/recipient-portal-sessions/{id}':
    get:
      summary: GetRecipientPortalSession
      operationId: getrecipientportalsession
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
    patch:
      summary: UpdateRecipientPortalSession
      operationId: updaterecipientportalsession
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  /oauth/embedded/token:
    get:
      summary: GetEmbeddedToken
      operationId: getembeddedtoken
      responses:
        '200':
          description: 
  '/transfer-requests-users/{id}/accept-tos':
    post:
      summary: AcceptTOSForTransferRequestUser
      operationId: accepttosfortransferrequestuser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  '/transfer-requests-users/{id}':
    get:
      summary: GetTransferRequestUserInfo
      operationId: gettransferrequestuserinfo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
