openapi: 3.0.0
info:
  version: '1.0'
  title: 'Transfer'
servers:
  - url: 'localhost:3000'
paths:
    /transfer/options/countriescurrencies:
        get:
            summary: 'Returns a list of countries and currencies available as a transfer destination'
            responses:
                '200':
                    description: ''
                    content:
                        application/json:
                            schema:
                                type: array
                                items: 
                                    $ref: '#/components/schemas/country'
components:
  schemas:
    country:
        type: object
        required:
        - name
        - iso3Code
        - currencies
        properties:
            name: 
                type: string
            iso3Code:
                type: string
                maxLength: 3
            currencies:
                type: array
                items: 
                    $ref: '#/components/schemas/currency'
    currency:
        type: object
        required:
        - name
        - iso3Code
        - symbol
        properties:
            name:
                type: string
            iso3Code:
                type: string
                maxLength: 3
            symbol:
                type: string
    errorPayload:
        type: object
        required:
        - errors
        properties: 
            errors:
                type: array
                items:
                  $ref: '#/components/schemas/error'
    error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          pattern: '[A-Z][A-Z][0-9]'
          description: 'User facing error code that can be used to look up error details by support'
        message:
          type: string
          description: 'User facing error message'
        description:
            type: string
            description: 'Detailed explanation of the error meant for debugging'