---
openapi: 3.1.0
info:
  title: Transfer Request API
  version: 1.0.1
  description: |
    The Transfer Request API enables creation, retrieval, and cancellation of Transfer Requests in the ReadyRemit system.
servers:
- url: https://sandbox-api.readyremit.com/transferrequests/v1
- url: https://api.readyremit.com/transferrequests/v1
webhooks:
  status:
    post:
      summary: Transfer Request Status Webhook
      description: |
        This endpoint is used to receive status updates for Transfer Requests.
        The endpoint will be called when the status of a Transfer Request changes.
        The endpoint should respond with a 200 status code.
        The status webhook will retry up to 5 times with a 5 second delay between each retry if a non-200 status code is returned.
        The URL for this endpoint must be provided to the ReadyRemit Integrations team.
      operationId: TransferRequestStatusWebhook
      requestBody:
        description: Post a status update to your webhook
        content:
          application/json:
            schema:
              type: object
              properties:
                transferRequestId:
                  type: string
                  description: Unique ID of the Transfer Request
                status:
                  type: object
                  properties:
                    id:
                      type: string
                      enum:
                      - UNKNOWN
                      - CREATED
                      - PROCESSING
                      - INVALID
                      - FAILED_TO_PROCESS
                      - PROCESSED
                      - CANCELED
                    name:
                      type: string
                  title: Status
                updatedAt:
                  type: string
                  format: date-time
                  description: Date and time when the Transfer Request was last updated in ISO 8601 format
      responses:
        '200':
          description: Webhook request accepted
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    error:
      type: object
      properties:
        code:
          type: string
          description: Code that categorizes an error. This value is locale agnostic.
        message:
          type: string
          description: Translated, user-facing error message.
        description:
          type: string
          description: Developer facing error message. This value should not be shown to an end user.
    transferRequest:
      type: object
      properties:
        referenceId:
          type: string
          description: >
            Unique ID used to reference the Transfer Request in future Status reports. This value is generated by you.
            Note: It is recommended to select a value that is already being used to reference this payment in your system.
        senderId:
          type: string
          description: >
            Unique ID provided by the ReadyRemit Integrations team referencing a specific sender configuration and account as the source of funds.
        firstName:
          type: string
          description: Given name of the recipient (e.g. Jose)
        lastName:
          type: string
          description: Surname of the recipient (e.g. Garcia)
        secondLastName:
          type: string
          description: Maternal or second last name of the recipient (e.g. Lopez)
        email:
          type: string
          description: Email address of the recipient. This will determine where notification emails are sent. (e.g. jgarcia@example.com)
        phone:
          type: string
          description: Phone number of the recipient (e.g. +1 555-555-5555)
        addressLine1:
          type: string
          description: Address line 1 of the recipient mailing address (e.g. 123 Main St)
        addressLine2:
          type: string
          description: Address line 2 of the recipient mailing address (e.g. Apt 123)
        city:
          type: string
          description: City of the recipient mailing address (e.g. Tokyo, New York)
        state:
          type: string
          description: State/Province of the recipient mailing address (e.g. NY, Guerrero)
        postalCode:
          type: string
          description: Zip/Postal code of the recipient mailing address (e.g. 10001, 12345)
        country:
          type: string
          description: Country of the recipient mailing address	in ISO 3 format (e.g. USA, JPN)
        rowCurrency:
          type: string
          description: Currency of the Transfer Request	source of funds in ISO 3 format (e.g. USD, JPY)
        quoteBy:
          type: string
          enum:
          - SEND_AMOUNT
          - RECEIVE_AMOUNT
          description: >
            Quoting by send or receive amount. Valid values are `SEND_AMOUNT` and `RECEIVE_AMOUNT`. 
            If the value is `SEND_AMOUNT` then the amount received by the recipient is flexible based on rates and the amount sent by you the client will be fixed.
            If the value is `RECEIVE_AMOUNT` then the amount received by the recipient is fixed, and the amount sent by you, the client, will vary by rate.
        supplementalInfo1:
          type: string
          description: Additional field for notes for cross reference	
        supplementalInfo2:
          type: string
          description: Additional field for notes for cross reference	
        createdAt:
          type: string
          format: date-time
          description: Date and time when the Transfer Request was created in ISO 8601 format (e.g. 2021-01-01T00:00:00.000Z)
        updatedAt:
          type: string
          format: date-time
          description: Date and time when the Transfer Request was last updated in ISO 8601 format (e.g. 2021-01-01T00:00:00.000Z)
      required:
      - referenceId
      - senderId
      - firstName
      - lastName
      - secondLastName
      - email
      - phone
      - addressLine1
      - addressLine2
      - city
      - state
      - postalCode
      - country
      - amount
      - rowCurrency
      - quoteBy
      - supplementalInfo1
      - supplementalInfo2
      additionalProperties: false
      title: TransferRequestRecord
    status:
      type: object
      properties:
        status:
          type: object
          properties:
            id:
              type: string
              enum:
              - UNKNOWN
              - CREATED
              - PROCESSING
              - INVALID
              - FAILED_TO_PROCESS
              - PROCESSED
              - CANCELED
            name:
              type: string
          title: Status
    amount:
      type: object
      description: |
        Amount of the Transfer Request. This could be the amount sent or received depending on the value of the `quoteBy` field.
      properties:
        value:
          type: number
          description: |
            Amount of the Transfer Request, normalized to the number of decimal places for the currency.
            Examples
            - For USD, the currency has 2 decimal places. So $10.95 would be represented as 1095.
            - For JPY, the currency has 0 decimal places. So ¥1000 would be represented as 1000.
        currency:
          type: object
          properties:
            name:
              type: string
              description: |
                Name of the currency. Examples: United States Dollar, Japanese Yen, etc. 
            iso3Code:
              type: string
              description: |
                ISO 4217 3-letter currency code. Examples: USD, JPY, etc.
            symbol:
              type: string
              description: |
                Currency symbol. Examples: $, ¥, etc.
            decimalPlaces:
              type: number
              description: |
                Number of decimal places for the currency. Examples: 2 for USD, 0 for JPY, etc.
      title: Amount
paths:
  "/oauth/token":
    post:
      summary: Authenticate
      description: Swap a Client ID and Client Secret for an OAuth Bearer token
      operationId: Authenticate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  description: |
                    Client ID provided by the ReadyRemit Integrations team. 
                    This value is unique to your organization and should be kept secret.
                client_secret:
                  type: string
                  description: |
                    Client Secret provided by the ReadyRemit Integrations team
                    This value is unique to your organization and should be kept secret.
                audience:
                  type: string
                  description: |
                    Audience provided by the ReadyRemit Integrations team
                grant_type:
                  type: string
                  description: |
                    Grant type will always be `client_credentials`
              required:
              - client_id
              - client_secret
              - audience
              - grant_type
              additionalProperties: false
        required: true
      responses:
        '200':
          description: Authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: |
                      Bearer token used to authenticate requests to the API.
                      This token is valid for 24 hours.
                  expires_in:
                    type: string
                    description: |
                      Number of seconds until the token expires.
                  token_type:
                    type: string
                    description: |
                      Type of token. This will always be `Bearer`.
                required:
                - access_token
                - expires_in
                - token_type
                additionalProperties: false
        4XX:
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                - type: array
                  items:
                    "$ref": "#/components/schemas/error"
                - type: object
                  properties:
                    message:
                      type: string
                    errors:
                      type: array
                      items:
                        "$ref": "#/components/schemas/error"
  "/transfer-requests":
    post:
      summary: Create Transfer Request
      description: >
        This operation takes in one or more Transfer Request records and ingests them into the ReadyRemit system. The response from this endpoint will be the list of processed Transfer Requets. 
        NOTE: This operation does not initiate any transfer of funds.
      operationId: CreateTransferRequest
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transferRequests:
                  type: array
                  items: 
                    allOf:
                    - type: object
                      name: amount
                      properties:
                        amount:
                          type: number
                          description: |
                            Amount of the Transfer Request, normalized to the number of decimal places for the currency.
                            Examples
                            - For USD, the currency has 2 decimal places. So $10.95 would be represented as 1095.
                            - For JPY, the currency has 0 decimal places. So ¥1000 would be represented as 1000.
                        verificationCode:
                          description: |
                            Verification code the recipient will need to provide to receive the funds.
                      required:
                      - amount
                      - verificationCode
                    - "$ref": "#/components/schemas/transferRequest"
                  minItems: 1
              required:
              - transferRequests
              additionalProperties: false
        required: true
      security:
      - Authorization: []
      responses:
        '201':
          description: Transfer Request created
          content:
            application/json:
              schema:
                type: object
                properties:
                  transferRequests:
                    type: array
                    description: >
                      List of Transfer Requests, both successful and failed.
                    items:
                      allOf:
                      - "$ref": "#/components/schemas/transferRequest"
                      - "$ref": "#/components/schemas/status"
                      - "$ref": "#/components/schemas/amount"
                  failedRecords:
                    type: array
                    items:
                      allOf:
                      - "$ref": "#/components/schemas/transferRequest"
                      - "$ref": "#/components/schemas/status"
                      - "$ref": "#/components/schemas/amount"
                additionalProperties: false
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                oneOf:
                - type: array
                  items:
                    "$ref": "#/components/schemas/error"
                - type: object
                  properties:
                    message:
                      type: string
                    errors:
                      type: array
                      items:
                        "$ref": "#/components/schemas/error"
  "/transfer-requests/{id}":
    get:
      summary: Get Transfer Request
      description: >
        This operation retrieves a Transfer Request by its ID.
      operationId: GetTransferRequest
      parameters:
      - schema:
          type: string
          format: uuid
        in: path
        name: id
        description: Unique ID of the Transfer Request
        required: true
      security:
      - Authorization: []
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                allOf:
                - "$ref": "#/components/schemas/transferRequest"
                - "$ref": "#/components/schemas/status"
                - "$ref": "#/components/schemas/amount"
        4XX:
          description: Default Response
          content:
            application/json:
              schema:
                oneOf:
                - type: array
                  items:
                    "$ref": "#/components/schemas/error"
                - type: object
                  properties:
                    message:
                      type: string
                    errors:
                      type: array
                      items:
                        "$ref": "#/components/schemas/error"
  "/transfer-requests/{id}/cancel":
    post:
      summary: Cancel Transfer Request
      description: >
        This operation attempts to cancel a Transfer Request that has not been completed.
        If a Transfer Request has already been processed, and the payment retrieved, cancellation is not availabile.
      operationId: CancelTransferRequest
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
                  enum:
                  - MAIL_CHECK
                  - INVALID
                reasonDescription:
                  type: string
                  minLength: 1
                  maxLength: 255
              required:
              - reason
              additionalProperties: false
        required: true
      parameters:
      - schema:
          type: string
          format: uuid
        in: path
        name: id
        required: true
      security:
      - Authorization: []
      responses:
        '200':
          description: Transfer Request canceled
          content:
            application/json:
              schema:
                allOf:
                  - "$ref": "#/components/schemas/transferRequest"
                  - "$ref": "#/components/schemas/status"
                  - "$ref": "#/components/schemas/amount"
        4XX:
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                - type: array
                  items:
                    "$ref": "#/components/schemas/error"
                - type: object
                  properties:
                    message:
                      type: string
                    errors:
                      type: array
                      items:
                        "$ref": "#/components/schemas/error"
  "/health":
    get:
      summary: Health Check
      description: >
        This endpoint is used for checking the health of the API. 
        It returns a 200 response if the API is running as expected.
      operationId: HealthCheck
      responses:
        '200':
          description: Transfer Request API healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
        4XX:
          description: Invalid request
          content:
            application/json:
              schema:
                oneOf:
                - type: array
                  items:
                    "$ref": "#/components/schemas/error"
                - type: object
                  properties:
                    message:
                      type: string
                    errors:
                      type: array
                      items:
                        "$ref": "#/components/schemas/error"