name: Sync `openapi spec` directory to ReadMe

# Run workflow when a new tag is pushed
on:
  push:
    tags:
      - 'v*' # This will match any tag that starts with 'v', like v1.0.0

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Extract tag name without the 'v' prefix (if you want just the version number)
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Run GitHub Action to sync docs in `documentation` directory
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          rdme: openapi postman/schemas/transfer.yml --key=${{ secrets.README_API_KEY }} --id=64e78fe5090fe300733e94fc --version=${{ env.VERSION }}
